services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=social'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=ubaid'
    ports:
      - '127.0.0.1:5987:5432'