server:
  port: 32000
spring:
  profiles:
    active: dev
  application:
    name: simple-spring-boot-with-jpa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5987
    username: ubaid
    password: secret
    hikari:
      pool-name: Hikari
      auto-commit: false
  liquibase:
    contexts: dev, faker
    change-log: classpath:config/liquibase/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
      hibernate.connection.release_mode: after_statement
      hibernate.stats.factory: dev.ubaid.ssbwj.service.stats.hibernate.TransactionStatisticsFactory
  docker:
    compose:
      file: simple-spring-boot-with-jpa/compose.yaml


logging:
  level:
    org.springframework.orm.hibernate5: trace
    org.springframework.orm.jpa: trace
    org.hibernate.sql: trace
    org.hibernate.resource.transaction: trace
    org.hibernate.resource.jdbc: trace
    org.hibernate.engine.transaction: trace
    org.hibernate.internal.SessionImpl: trace
    org.hibernate.internal.SessionFactoryImpl: trace
    liquibase: debug
