server:
  port: 32001

spring:
  profiles:
    active: dev
  application:
    name: simple-spring-boot-with-jpa-inheritance
  datasource:
    url: jdbc:postgresql://localhost:5988
    type: com.zaxxer.hikari.HikariDataSource
    username: ubaid
    password: changeme
#    hikari:
#      pool-name: Hikari
#      auto-commit: false
#  jpa:
#    hibernate:
#      ddl-auto: none
#    open-in-view: false
#    properties:
#      'hibernate.format_sql': true
#      'hibernate.connection.autocommit': false
#      'hibernate.connection.release_mode': after_transaction
#  docker:
#    compose:
#      file: simple-spring-boot-with-jpa-inheritance/compose.yml
      
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: debug
    dev.ubaid: debug
    root: debug