name: Test Simple Spring Boot with JPA and having inheritance

on:
  push:
    paths:
      - 'simple-spring-boot-with-jpa-inheritance/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'maven'
      - name: Build and Test
        run: |
          cd simple-spring-boot-with-jpa-inheritance
          mvn clean verify