name: Test Spring Application Context

on:
  push:
    paths:
      - 'spring-application-context/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'maven'
      - name: Build and Test
        run: |
          cd spring-application-context
          mvn clean verify